import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/pages/Header";
import Footer from "../../components/pages/Footer";
import Home from "../../components/pages/Home";
import About from "../../components/pages/About";
import Contact from "../../components/pages/Contact";
import Portofolios from "../../components/pages/Portofolios";

const inter = Inter({ subsets: ["latin"] });

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Profile Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className="mb-14 block">
        {/* Home Section */}
        <section id="home-section" className="relative px-3">
          <Home />
        </section>

        {/* About Section */}
        <section id="about-section" className="px-10 py-10 lg:px-20 lg:py-20">
          <About />
        </section>

        {/* Contact Section */}
        <section id="contact-section" className="px-10 py-10 lg:px-20 lg:py-20">
          <Contact />
        </section>

        {/* Portofolion Section */}
        <section
          id="portofolios-section"
          className="px-10 py-10 lg:px-20 lg:py-20"
        >
          <Portofolios />
        </section>
      </section>

      <Footer />
    </>
  );
}
