import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../../components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Profile Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className="all-content-section">
        {/* Home Section */}
        <section className="home-section">
          <h1 className="text-3xl font-bold underline">HOME</h1>
        </section>

        {/* About Section */}
        <section className="about-section">
          <h1>ABOUT</h1>
        </section>

        {/* Contact Section */}
        <section className="contact-section">
          <h1>CONTACT</h1>
        </section>

        {/* Portofolion Section */}
        <section className="portofolio-section">
          <h1>PORTOFOLIO</h1>
        </section>
      </section>
    </>
  );
}
